rules = [
  DisableSyntax,
  OrganizeImports
]

DisableSyntax = {
  noVars = true
  noThrows = true
  noNulls = true
  noReturns = true
  noWhileLoops = true
  noAsInstanceOf = true
  noIsInstanceOf = true
  noXml = true
  noDefaultArgs = true
  noFinalize = true
  noValPatterns = true
}

OrganizeImports = {
  targetDialect = Scala3
  blankLines = Manual
  expandRelative = true
  groupedImports = Explode
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  groups = [
    "java",
    "javax",
    "scala",
    "---",
    "boilerplate",
    "cats",
    "fs2",
    "com.comcast.ip4s",
    "---",
    "*",
    "---",
    "emile"
  ]
  removeUnused = true
}
